services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logisticsdb
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/isql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build:
      context: ./backend/RutasLogisticas
      dockerfile: Dockerfile
    container_name: spring_backend
    restart: always
    ports:
      - "${BACKEND_PORT}:8080"
    env_file: .env
    depends_on:
      - db

  auth-service:
    build:
      context: ./auth/RutasLogisticas
      dockerfile: Dockerfile
    container_name: auth_service
    restart: always
    ports:
      - "8081:8081"
    env_file: .env
    depends_on:
      - db

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway_service
    restart: always
    ports:
      - "8082:8082"
    env_file: .env
    depends_on:
      - auth-service
      - backend

  frontend:
    build:
      context: ./frontend/frontend-app
      dockerfile: Dockerfile
    container_name: angular_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    env_file: .env
    depends_on:
      - backend

volumes:
  db_data:
