services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logisticsdb
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend/RutasLogisticas
      dockerfile: Dockerfile
    container_name: spring_backend
    restart: always
    ports:
      - "${BACKEND_PORT}:8080"
    env_file: .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/frontend-app
      dockerfile: Dockerfile
    container_name: angular_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - gateway

  auth-service:
    build:
      context: ./auth/RutasLogisticas
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/logisticsdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
    - "${AUTH_PORT}:8081"
    depends_on:
      - db


  gateway:
    build: ./gateway
    container_name: gateway_service
    environment:
      SERVER_PORT: 8082
    ports:
      - "${GATEWAY_PORT}:8082"
    depends_on:
      - backend
      - auth-service

volumes:
  db_data: