version: '3.9'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rutas-net

  gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    ports:
      - "${BACKEND_GATEWAY_PORT}:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql_db
      - logistics
    networks:
      - rutas-net

  logistics:
    build:
      context: ./backend/logistics
      dockerfile: Dockerfile
    container_name: logistics
    restart: always
    ports:
      - "${BACKEND_LOGISTICS_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql_db
    networks:
      - rutas-net

  frontend:
    build:
      context: ./frontend/frontend-app
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - gateway
    networks:
      - rutas-net

networks:
  rutas-net:

volumes:
  mysql_data:
