server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql_db:3306/logisticsdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    serialization.write-dates-as-timestamps: false
